[package]
name = "networkcoding"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustrlc = { path = "../rustrlc"}
rustgf = { path = "../rustgf"}
byteorder = "1.4.3"
tinymt = "1.0"
rand = "0.8.4"

